GET http://localhost:3000/api/post/ HTTP/1.1

###
POST http://localhost:5000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username":"cwecfew",
    "email":"edwe@gmail.com",
    "password":"werwewe"
}

###
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username":"brawsefewia",
    "password":"werewerwewe"
}
###
PUT http://localhost:3000/api/user/615afea285088bd9d1aa2af0 HTTP/1.1
Content-Type: application/json

{
    "userId" : "615afea285088bd9d1aa2af0",
    "username":"ewsd",
    "password":"wathuvdseew"
}
###
DELETE http://localhost:3000/api/user/6131d7e27ce9ece9a3404bc7  HTTP/1.1

###
GET http://localhost:3000/api/user/615afea285088bd9d1aa2af0 HTTP/1.1

###
GET http://localhost:5000/api/post/615affdd85088bd9d1aa2afb HTTP/1.1
###
POST http://localhost:5000/api/post/ HTTP/1.1
Content-Type: application/json

{
    "title" : "Mental ",
    "desc" : "We thought we’d pop a list together of the blogs we frequently read, admire and appreciate. We hope you enjoy them as we do.1. THE MIGHTYThe Mighty publish real stories by real people, living with disability, disease and mental illness. They aim to build a safe platform for their community to share their stories, connect with others and raise support for the causes they believe in. Their mental illness section is excellent, and covers a wide range of conditions.2. THE SECRET LIFE OF A MANIC DEPRESSIVEWriter and mental health activist Seaneen started The Secret Life of a Manic Depressive ten years ago and has been sharing her experiences of being mentally interesting since. We love Seaneen’s humour, and warm, informal tone, as well as her furious, hastily typed and unspellchecked rants.",
    "username":"jane",
    "category":"health",
    "photo":"blabla.jpg"
}

###
PUT http://localhost:5000/api/post/615affdd85088bd9d1aa2afb HTTP/1.1
Content-Type: application/json

{   
    "title" : "the  post",
    "desc" : " post",
    "username":"jane",
    "category":"wathuvdseew"
}
###
DELETE http://localhost:5000/api/post/6134ffc7e23b3d3d6ab41e89  HTTP/1.1
Content-Type: application/json

{   
    "title" : "the  post",
    "desc" : " post",
    "username":"jane",
    "category":"music"
}

###
GET http://localhost:5000/api/post/?cat=music HTTP/1.1
 
#  {
#      "username":"jane",
#      "title":"the new post",
#  }

###
POST http://localhost:5000/api/cat/ HTTP/1.1
Content-Type: application/json


{
    "name":"music"
}
###
GET http://localhost:5000/api/cat/ HTTP/1.1

###
POST http://localhost:3000/api/upload/ HTTP/1.1
Content-Type: application/json
